title: Konradusko Blog
cacheRefreshTime: 1
mainPagePosts: 1
tagsPagePosts: 1
template: standard
allowJsonData: true
login: test
password: test 
template_data:
  footer:
    companyName: test
    fb_link: 
    twitter_link:
    instagram_link:
    github_link: 
  links:
    homePage: /
    tagsPage: /tags