
cacheRefreshTime: 1
mainPagePosts: 4
tagsPagePosts: 1
template: standard
allowJsonData: true
login: test
password: test 
template_data:
  title: Konradusko Blog
  nav:
    logoSrc: https://avatars.githubusercontent.com/u/42543331?v=4
  footer:
    companyName: test
    fb_link: 
    twitter_link:
    instagram_link:
    github_link: 
  links:
    homePage: /
    tagsPage: /tags
    singleTagPage: /tag/